name: Zenoss Control Center
author: Zenoss
markdown: redcarpet
highlighter: true
baseurl:
description: Zenoss Control Center
github: http://www.github.com/zenoss
#twitter: http://www.twitter.com/zenoss
#facebook: http://www.facebook.com/zenoss
#linkedin: http://www.linkedin.com
#email: info@zenoss.com
#location: 42°2'16"N   70°12'47"W
#disqus: diqus-username

##Make sure to edit the above fields, especially for disqus.

